import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AnimatePresence } from "framer-motion";

export const metadata: Metadata = {
  title: "Copy-Trades",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <AnimatePresence>
        <html lang="en">
          <body className={`antialiased`}>{children}</body>
        </html>
      </AnimatePresence>
    </ThemeProvider>
  );
}
