import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AnimatePresence } from "framer-motion";
import { PersistProviders, Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import AppInitializer from "./app-initializer";

export const metadata: Metadata = {
  title: "CopyTradeMarkets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PersistProviders>
      <ThemeProvider>
        <Providers>
          <AppInitializer>
            <AnimatePresence>
              <html lang="en">
                <body className={`antialiased`}>
                  <main>{children}</main>
                  <Toaster />
                </body>
              </html>
            </AnimatePresence>
          </AppInitializer>
        </Providers>
      </ThemeProvider>
    </PersistProviders>
  );
}
